FROM python:3.12-slim

WORKDIR /code

COPY parser_service/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY parser_service ./parser_service

CMD ["uvicorn", "parser_service.main:app", "--host", "0.0.0.0", "--port", "8001"]